DATAS  SEGMENT
	STRING  DB  'Hello World!',13,10,'$'
DATAS  ENDS

CODES  SEGMENT
    ASSUME    CS:CODES,DS:DATAS
START:
    MOV  AX,DATAS
    MOV  DS,AX
    LEA  DX,STRING
    MOV  AH,9
    INT  21H
	;调用int 21h功能并输出
    MOV  AH,4CH
    INT  21H
CODES  ENDS
    END   START